import { useState } from 'react'
import { Box, Typography, TextField, MenuItem, Button, Card, CardContent } from '@mui/material'
import { CATEGORIES } from '../utils/Constants'
import { useNavigate } from 'react-router-dom'

function SubmitComplaint() {
  const navigate = useNavigate();
  
  const [values, setValues] = useState({ title: '', category: '', location: '', description: '' })

  const [submitted, setSubmitted] = useState(false)

  const handleChange = field => event => {
    setValues(prev => ({...prev, [field]: event.target.value }))
  }

  const handleSubmit = event => {
    event.preventDefault()
    //autogenerated id 
    const existing = JSON.parse(localStorage.getItem('complaints') || '[]');
    const nextNumber = existing.length + 1;
    const complaintId = `E${nextNumber}`;
    
    const newComplaint = {id: complaintId,...values,dateSubmitted: new Date().toLocaleDateString('en-GB'), // Auto date
      status: 'Pending' // Auto status
    };
    localStorage.setItem('complaints', JSON.stringify([...existing, newComplaint]));
    navigate('/'); // Redirect to My Complaints page

  }

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ 
        bgcolor: '#012243', 
        color: '#ffffff', 
        p: 3, 
        mb: 3, 
        borderRadius: 2,
        boxShadow: 2
      }}>
        <Typography variant="h5" mb={1}>Submit a New Complaint</Typography>
        <Typography variant="body2">
          Fill in the details below to add a complaint to the system.
        </Typography>
      </Box>

      <Card>
        <CardContent>
          <Box component="form" noValidate autoComplete="off" onSubmit={handleSubmit} sx={{ display: 'grid', gap: 2 }}>
            
            <TextField
              label="Complaint Title"
              value={values.title}
              onChange={handleChange('title')}
              required
            />
            
            <TextField
              select
              label="Category"
              value={values.category}
              onChange={handleChange('category')}
              required
            >
              {CATEGORIES.map((option) => (
                <MenuItem key={option} value={option}>
                  {option}
                </MenuItem>
              ))}
            </TextField>
            
            <TextField
              label="Location"
              value={values.location}
              onChange={handleChange('location')}
              required
            />
            
            <TextField
              label="Description"
              multiline
              rows={4}
              value={values.description}
              onChange={handleChange('description')}
              required
            />
            
            <Button type="submit" variant="contained">Submit</Button>
          </Box>
        </CardContent>
      </Card>
    </Box>
  )
}

export default SubmitComplaint