import PendingActionsIcon from '@mui/icons-material/PendingActions';
import SyncIcon           from '@mui/icons-material/Sync';
import CheckCircleIcon    from '@mui/icons-material/CheckCircle';
import HelpOutlineOutlinedIcon    from '@mui/icons-material/HelpOutlineOutlined';
import { Chip }           from '@mui/material';

// ─── Status chip ──────────────────────────────────────────────────────────────
// Renders a coloured MUI Chip for a complaint status string.
// Used across AdminComplaintList, StatusUpdateScreen, dashboards, etc.
const statusChip = (status) => {
  const map = {
    'Pending':      { color: 'primary', icon: <PendingActionsIcon sx={{ fontSize: 14 }} /> },
    'In Progress':  { color: 'warning', icon: <SyncIcon           sx={{ fontSize: 14 }} /> },
    'Resolved':     { color: 'success', icon: <CheckCircleIcon    sx={{ fontSize: 14 }} /> },
  };
  const cfg = map[status] || { color: 'default', icon: <HelpOutlineOutlinedIcon sx={{ fontSize: 14 }} /> };

  return (
    <Chip
      label={status || 'Unknown'}
      color={cfg.color}
      icon={cfg.icon}
      size="small"
      variant="filled"
      sx={{ fontWeight: 600 }}
    />
  );
};

export default statusChip;

// ─── NOTE ─────────────────────────────────────────────────────────────────────
// uid() has been removed — complaint and user IDs are now generated by MongoDB
// as ObjectId values and returned from the API.